name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCF9vbHlZpz7FbOAky3fnYxw
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_AFTERTHERAIN }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_AFTERTHERAIN }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`의학채널 비온뒤 - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
